import { world, system, ItemStack } from "@minecraft/server";

// ============================================
// ชุดธรรมดาา Skin Lock System
// Generated by Skin Factory V2
// ============================================

const ALLOWED_PLAYERS = ["Iamsayhi1", "muimuigame"];
const SELECTOR_ITEM = "heaver:heaver_chudtrrmdaa_epaw_selector";
const SKIN_ITEM = "heaver:heaver_chudtrrmdaa_epaw";
const SLOT_NAME = "Chest";

function showActionBar(player, message) {
    player.onScreenDisplay.setActionBar(message);
}

// Selector item use - Equip skin
world.afterEvents.itemUse.subscribe((event) => {
    const player = event.source;
    const item = event.itemStack;

    if (item?.typeId !== SELECTOR_ITEM) return;

    if (!ALLOWED_PLAYERS.includes(player.name)) {
        showActionBar(player, "§c§r§fคุณไม่มีสิทธิ์ใช้งานไอเทมนี้!");
        return;
    }

    system.run(() => {
        equipSkin(player);
    });
});

function equipSkin(player) {
    try {
        const equipment = player.getComponent("equippable");
        if (!equipment) {
            showActionBar(player, "§c§l[ชุดธรรมดาา] §r§fไม่สามารถเข้าถึง equipment ได้!");
            return;
        }

        const currentItem = equipment.getEquipment(SLOT_NAME);
        if (currentItem?.typeId === SKIN_ITEM) {
            equipment.setEquipment(SLOT_NAME, undefined);
            showActionBar(player, "§c§l[ชุดธรรมดาา] §r§fถอดสกินแล้ว!");
            return;
        }

        const skinStack = new ItemStack(SKIN_ITEM, 1);
        equipment.setEquipment(SLOT_NAME, skinStack);
        showActionBar(player, "§a§l[ชุดธรรมดาา] §r§fสวมใส่สกินแล้ว!");
    } catch (e) {
        showActionBar(player, "§c§l[ชุดธรรมดาา] §r§fเกิดข้อผิดพลาด!");
    }
}

// Give selector item to allowed players on spawn/respawn
world.afterEvents.playerSpawn.subscribe((event) => {
    const player = event.player;
    
    // Only give item to allowed players
    if (!ALLOWED_PLAYERS.includes(player.name)) return;
    
    system.runTimeout(() => {
        try {
            const inventory = player.getComponent("inventory");
            if (!inventory) return;
            
            const container = inventory.container;
            if (!container) return;
            
            // Check if player already has the selector item
            for (let i = 0; i < container.size; i++) {
                const item = container.getItem(i);
                if (item?.typeId === SELECTOR_ITEM) {
                    return; // Already has item, don't give another
                }
            }
            
            // Give the selector item
            const selectorStack = new ItemStack(SELECTOR_ITEM, 1);
            container.addItem(selectorStack);
            showActionBar(player, "§a§l[ชุดธรรมดาา] §r§fได้รับ Selector Item แล้ว!");
        } catch (e) {
            // Ignore errors
        }
    }, 20); // Small delay to ensure player is fully loaded
});

// Prevent non-allowed players from wearing
system.runInterval(() => {
    for (const player of world.getAllPlayers()) {
        if (ALLOWED_PLAYERS.includes(player.name)) continue;

        try {
            const equipment = player.getComponent("equippable");
            if (!equipment) continue;

            const item = equipment.getEquipment(SLOT_NAME);
            if (item?.typeId === SKIN_ITEM) {
                equipment.setEquipment(SLOT_NAME, undefined);
                showActionBar(player, "§r§fคุณไม่มีสิทธิ์สวมใส่สกินนี้!");
            }
        } catch (e) {
            // Ignore errors
        }
    }
}, 20);
