# SAN - Invisibility Effect
# Generated by Skin Factory V3

effect @a[hasitem={item=heaver:heaver_san1_tc1e,location=slot.armor.legs}] invisibility 5 255 true
effect @a[hasitem={item=heaver:heaver_ssl2_qhxu,location=slot.armor.legs}] invisibility 5 255 true
effect @a[hasitem={item=heaver:heaver_sby3_ajpr,location=slot.armor.legs}] invisibility 5 255 true